# Generated by Django 2.1.5 on 2019-01-08 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('locale', models.CharField(default='en_IN', max_length=10)),
                ('birthyear', models.IntegerField(default=1970)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('location', models.CharField(default='Delhi', max_length=250)),
                ('timezone', models.IntegerField(default=0)),
                ('friends', models.ManyToManyField(related_name='_appuser_friends_+', to='ideal_event.AppUser')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(blank=True, max_length=250)),
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails')),
                ('start_time', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideal_event.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideal_event.AppUser')),
            ],
        ),
    ]
