# Generated by Django 2.1.5 on 2019-01-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user_id',
        ),
        migrations.AddField(
            model_name='appuser',
            name='interests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ideal_event.Interest'),
            preserve_default=False,
        ),
    ]
