# Generated by Django 2.1.5 on 2019-01-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_event', '0004_auto_20190108_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest2',
            name='interest_name',
        ),
        migrations.AddField(
            model_name='interest2',
            name='interest_name',
            field=models.ManyToManyField(to='ideal_event.Interest'),
        ),
    ]
