# Generated by Django 2.1.5 on 2019-01-08 15:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_event', '0007_auto_20190108_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('interest_level', models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideal_event.Interest')),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='interests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideal_event.Interest'),
        ),
    ]
