# Generated by Django 2.1.5 on 2019-01-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_event', '0009_auto_20190108_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='interests',
        ),
        migrations.AddField(
            model_name='appuser',
            name='interests',
            field=models.ManyToManyField(to='ideal_event.KeyVal'),
        ),
    ]
