# Generated by Django 2.1.5 on 2019-01-08 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_event', '0011_auto_20190108_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('appUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideal_event.AppUser')),
            ],
        ),
    ]
