# Generated by Django 2.1.5 on 2019-01-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_event', '0012_grp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grp',
            name='appUsers',
        ),
        migrations.AddField(
            model_name='grp',
            name='appUsers',
            field=models.ManyToManyField(to='ideal_event.AppUser'),
        ),
    ]
