# Generated by Django 2.1.5 on 2019-01-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_event', '0014_interest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='height_field',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='interest',
            name='width_field',
            field=models.IntegerField(default=500),
        ),
    ]
